name: GitHub-Game-of-Life

on:
  schedule:
    - cron: "0 0 * * *" # Runs every 24 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-game-of-life
    steps:
      - uses: actions/checkout@v3
      - uses: eatsjobs/game-of-life@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Update Game of Life"
          # This generates the simulation
